name: Build PyPi package

on: [push, pull_request]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install build dependencies
        run: python -m pip install build wheel

      - name: Build distributions
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel
      
      - name: Publish package to test PyPI
        if: github.repository == 'toncenter/pytonlib' && github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/

      # - name: Publish package to PyPI
      #   if: github.repository == 'toncenter/pytonlib' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.ref == 'refs/heads/main'
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_PASSWORD }}
      #     repository_url: https://upload.pypi.org/legacy/
